import './listeners/index';
import '@main/helpers/LogConfiguration';
import { app, BrowserWindow, Menu, nativeImage, Tray } from 'electron';
import * as path from 'path';
import { createMainWindow, isDevEnv } from '@main/helpers/AppLifeCycleHelper';
import { launchUpdatePackageJob } from './jobs/PackageJobs';
import log from 'electron-log';
import i18n from './i18n';
import { patchNonceForProtocols } from './helpers/CspHelper';

if (isDevEnv()) {
  app.setPath('userData', app.getPath('userData') + '-dev');
}

log.debug(`UserData path is "${app.getPath('userData')}"`);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

export let mainWindow: BrowserWindow | undefined;

export const ressourcePathFolder = path.join(__dirname, 'ressources');

function quitApp(): void {
  log.info('Exiting app');
  app.quit();
}

function reopenApp(): void {
  log.info('Reopen app');
  if (!mainWindow || mainWindow.isDestroyed()) {
    log.debug('Create a main window');
    mainWindow = createMainWindow(
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      MAIN_WINDOW_WEBPACK_ENTRY,
    );
  } else {
    log.debug('Push main window to front');
    mainWindow.show();
  }
}

const singleInstanceLock = app.requestSingleInstanceLock();
if (!singleInstanceLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    reopenApp();
  });
}

app.on('ready', () => {
  log.info('Opening app');

  patchNonceForProtocols();

  // Set Tray Icon
  const icon = nativeImage.createFromPath(
    path.join(ressourcePathFolder, 'logo.png'),
  );
  const trayIcon = new Tray(icon);
  trayIcon.setToolTip(i18n.t('tray.tooltip'));
  trayIcon.addListener('click', reopenApp);

  // Create Tray menu
  const trayMenu = Menu.buildFromTemplate([
    {
      label: i18n.t('tray.open'),
      type: 'normal',
      click: reopenApp,
    },
    {
      label: i18n.t('tray.close'),
      type: 'normal',
      click: quitApp,
    },
  ]);
  trayIcon.setContextMenu(trayMenu);

  // Start Jobs
  launchUpdatePackageJob();
});

app.on('window-all-closed', () => {
  log.info('All window closed, staying in background...');
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindow = createMainWindow(
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      MAIN_WINDOW_WEBPACK_ENTRY,
    );
  }
});

// Configure the app to automatically start at user login
app.setLoginItemSettings({
  openAtLogin: true,
});
