import { app, BrowserWindow } from 'electron';
import log from 'electron-log';
import * as path from 'path';
import { appIcon } from './AppIconHelper';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string | null;
declare const MAIN_WINDOW_VITE_NAME: string;

export const isDevEnv = (): boolean => {
  return (
    process.env.ENVIRONMENT !== undefined && process.env.ENVIRONMENT === 'DEV'
  );
};

const computeMainWindowEntry = (): string => {
  return (
    MAIN_WINDOW_VITE_DEV_SERVER_URL ??
    path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`)
  );
};

export const createMainWindow = (): BrowserWindow => {
  log.info('Create main Window');

  const mainWindowEntry = computeMainWindowEntry();
  log.debug(`Main window entry : ${mainWindowEntry}`);
  const preloadEntry = path.join(__dirname, 'preload.js');
  log.debug(`Preload entry : ${preloadEntry}`);

  const mainWindow = new BrowserWindow({
    title: 'Node Package Notifier',
    height: 1050,
    minHeight: 530,
    width: 1650,
    minWidth: 900,
    icon: appIcon,
    webPreferences: {
      preload: preloadEntry,
    },
  });

  if (app.isPackaged) {
    mainWindow.removeMenu();
  }
  void mainWindow.loadURL(mainWindowEntry);

  return mainWindow;
};
